apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wbt1gf5yb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbt1gf5yb-python 
  name: wbt1gf5yb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wbt1gf5yb-python 
